title: Wenxuan Zhou 周文轩
url: "https://wzhouad.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-185054764-1

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?hl=en&user=HHvcwrIAAAAJ&view_op=list_works&sortby=pubdate"
 - name: "Github"
   link: "https://github.com/wzhouad"
